import esbuild from "esbuild";
import process from "process";
// Node's own built-in module list (replaces the `builtin-modules` package, which
// eslint-plugin-obsidianmd's depend/ban-dependencies flags). Externalising every
// builtin is what lets the vendored engine code call `require("child_process")`
// lazily, inside a Platform.isDesktop guard, without esbuild trying to bundle it.
import { builtinModules as builtins } from "node:module";

const banner = `/*
This file is auto-generated by esbuild. Edit the source in src/ instead.
Effort Index
*/`;

const prod = process.argv.includes("production");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  minify: prod,
  treeShaking: true,
  outfile: "main.js",
  platform: "browser",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
